### ISSUE TITLE
Add support for Monocle lenses.

### ISSUE THREAD

**Issue by markhibberd** [argonaut-io/argonaut#100]
Looks like monocle is going to win the race to having a decent lens implementation. Still need to decide if it should sit on top of argonaut (i.e. argonaut-monocle, or we should just depend on it) - will largely depend on plans for binary/source compatibility for monacle.

https://github.com/julien-truffaut/Monocle

**Comment by julien-truffaut** [comment]
I added a few Monocle optics but I haven't duplicated all scalaz ones. I wonder how far do you want to go? i.e. stay as it is now, add Monocle optics for all scalaz optics, deprecate scalaz optics and replace them by Monocle ones

**Comment by seanparsons** [comment]
I'd prefer to leave the scalaz ones if possible, it would be interesting to know what people are clamouring for in this department.

**Comment by seanparsons** [comment]
Done.
