### ISSUE TITLE
Printer improvements.

### ISSUE THREAD

**Issue by markhibberd** [argonaut-io/argonaut#117]
Like #116, this is something that needs to happen before 6.1, but I don't have time to do at the moment. So I am documenting here in the hope that someone else does.

 - [x] Pretty params should be a case class, as it stands we can't change it without breaking binary compat, and it is really clumsy to use as the lens api does not compose will for setting multiple fields. Related to #96.
 - [x] Add pretty param support for a few extra variables, see #72 #92.
 - [x] Add monacle lenses for pretty params.
 - [x] Add support in PrettyParams and printer for dropping _null_ values from output (basically if an object has a value which is null, the corresponding key should not be included in the json) - this should default to off, but be easy to switch on.

**Comment by refried** [comment]
A bunch of these are done, right?

**Comment by seanparsons** [comment]
The last one definitely is.

**Comment by seanparsons** [comment]
Done.
