### ISSUE TITLE
Make DecodeResult covariant again

### ISSUE THREAD

**Issue by tixxit** [argonaut-io/argonaut#137]
I understand making many things invariant, but it seems like Scalaz has generally come down on data structures retaining their covariance. Argonaut seems to be a lot stricter. I have a lot of code like:

```scala
sealed trait Abc
case class A(...) extends Abc
case class B(...) extends Abc
case class C(...) extends Abc

private val aCodec = casecodeN(A.apply, A.unapply)
private val bCodec = casecodeN(B.apply, B.unapply)
private val cCodec = casecodeN(C.apply, C.unapply)

implicit val abcCodec = CodecJson({ ... }, { j => aCodec(j) ||| bCodec(j) ||| cCodec(j) })
```

Making DecodeResult invariant has made my little `|||` line turn into a rather ugly monster of vacuous maps. Any chance we could revert to covariance for some types? At least for simple data structures like DecodeResult.

**Comment by kareblak** [comment]
Whatever happened to this one?

**Comment by seanparsons** [comment]
@kareblak I'm probably going to revisit it very soon once "The Big Refactor" has been done.

**Comment by tonymorris** [comment]
:-1:

**Comment by seanparsons** [comment]
@tonymorris Yeah, tell me about it, it just causes grief otherwise.

**Comment by seanparsons** [comment]
@tixxit I'll reopen it so that I know I need to sort it.

**Comment by seanparsons** [comment]
Done.
