### ISSUE TITLE
6.1-SNAPSHOT on sonatype

### ISSUE THREAD

**Issue by alexarchambault** [argonaut-io/argonaut#160]
Are you guys pushing the very last developments on a public repo (sonatype, ...) ? I can only find an old version (with no auto codec) this way.

**Comment by seanparsons** [comment]
We haven't been pushing snapshots but 6.1-M5 was pushed before Christmas and that's only a couple of commits behind master.

**Comment by alexarchambault** [comment]
Found it, thanks.

**Comment by alexarchambault** [comment]
README seems to imply that the latest revision is published as 6.1-SNAPSHOT by the way, which is not the case.

**Comment by seanparsons** [comment]
Ah, righto, I might look at getting that sorted at least.

**Comment by seanparsons** [comment]
This is now sorted.

**Comment by alexarchambault** [comment]
Is it? README mentions 6.2-SNAPSHOT, which can't be found at https://oss.sonatype.org/content/repositories/snapshots/io/argonaut/ .

**Comment by seanparsons** [comment]
Whenever we next get an incompatible change that'll make an appearance, I'm not going to keep adding and removing that line each time we do a release!
