### ISSUE TITLE
Inability to co-inhabit with monocle

### ISSUE THREAD

**Issue by kryptt** [argonaut-io/argonaut#163]
Probably unrelated to #100, but it is not possible to define ones own CodecJson when monocle is in the compilers Classpath. This is probably a bug in scalac, but I don't have the ability to effectively debug this any further since my experience with both argonaut and monocle is 0 (I only just decided to use them together with http4s) 

@julien-truffaut might be able to shed more light into this as well

This [project](https://drive.google.com/file/d/0B1WejOuDTmITalhNeWlDa21fNUE/view?usp=sharing) shocases the problem at hand. 

Monocle 1.0.1 and Argonaut 6.1-M5 exhibit this issue.

Any ideas on what might be happening here?

**Comment by xuwei-k** [comment]
this is not scalac bug. 

- Argonaut 6.1-M5 depends on monocle 0.5.1
- Monocle 0.5.1 and 1.0.1 are binary incompatible

**Comment by julien-truffaut** [comment]
I upgraded monocle dependency in master to 1.0.1. I suppose it will go on the next milestone release or 6.1.

**Comment by jedws** [comment]
@xuwei-k what evidence is there that this is not a scalac bug?

apart from it being a generally good null hypothesis, this code is entirely prosaic and it is the mere presence of monocle that causes the compilation error…

**Comment by seanparsons** [comment]
Well it is a scalac bug as it shouldn't StackOverFlowError, but it's because those project versions are incompatible.

**Comment by kryptt** [comment]
Thanks @julien-truffaut @xuwei-k @seanparsons , I think I will post this to scalac, I don't believe the compiler should ever fall into this type of loop..
