### ISSUE TITLE
CodecJson not serializable.

### ISSUE THREAD

**Issue by parkx408** [argonaut-io/argonaut#165]
First of all, I have been using argonaut for awhile now and I really like it. Thanks!

We work with Spark extensively and I just pulled in argonaut as a dependency against some of my colleagues displeasure. 

Typically, it works fine but when I actually try to create an implicit functions that extends RDD (a distributed compute graph interface), I am running into issues. 

```
implicit class KeyValueDStreamExtension[V](self: DStream[(Key,V)]) extends Serializable {
    def saveToHBase(conf: Configuration)(implicit codec: EncodeJson[V]) =
        ...
}
```

Compiles fine but at runtime throws java.io.NotSerializableException.

```
Exception in thread "main" org.apache.spark.SparkException: Task not serializable
        ...
Caused by: java.io.NotSerializableException: argonaut.CodecJson$$anon$1
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1183)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1547)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1508)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1431)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1177)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:347)
	at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:42)
	at org.apache.spark.serializer.JavaSerializerInstance.serialize(JavaSerializer.scala:73)
	at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:164)
	... 6 more
```

Maybe there is a better way or maybe you guys can make the Codec serializable, I am not sure but any help would be greatly appreciated. 

Thanks!

**Comment by seanparsons** [comment]
So most of the EncodeJson/DecodeJson/CodecJson instances in theory should be possible to make them serializable because there's not much state involved. The only thing I'm wary of is that we'd need to write a whole load of extra tests to ensure it works well and this would be something we'd have to maintain forever.

**Comment by parkx408** [comment]
Thanks for the fast response. 
It sounds like a weak no? 
I think I can help with the patch and tests - but beware that I am no Scala expert and you may need to review carefully. 
Another thing is that Spark and other Scala based distributed frameworks are fairly popular right now and it may be worth the effort to support them.

Let me know how you guys want to go. Depending on the response, I can hack around it for now or will have to restructure the code.

**Comment by markhibberd** [comment]
@parkx408 @seanparsons The _best_ way to do this, is simply to change the `trait` and the `apply` method on the companion to be a case class. This should be done anyway for other reasons, such as making it easier to add methods without breaking binary compatibility.

**Comment by parkx408** [comment]
@markhibberd Thanks for the hint. Sadly, it is more terse than my skills would allow me to understand. I am loosing confidence that this is really something I can help with. 

Can you elaborate a little more on
> change the trait and the apply method on the companion to be a case class

?

**Comment by markhibberd** [comment]
@parkx408 No worries, sorry about that. 

An example of the style that is currently there for Encode and Decode Json.:

```
/* A type class for converting things to strings */
sealed trait FooDec[A] {
  def encode(x: A): String

  ... lots more operations that are not abstract ...
}

object FooDec {
  def apply[A](impl: A => String): FooDec[A] = new FooDec[A] {
    def encode(foo: Foo): String = impl(foo)
  }

  .. other stuff ...
}
```

This uses a sealed trait and an explicit constructor function to build instances of the type class.
This is would translate into a case class that can be instantiated directly.  You will see that many other data types have had similar translations for example HCursor (https://github.com/argonaut-io/argonaut/commit/c4e27fce256509a2d75ea7519b4d617a7dd08cd3#diff-71de05d0f339d28d0a4dbadf155cc764R5).

```
case class FooDec(encode: A => String /* or what ever the abstract function is */) {
}

object FooDec {
  // No apply
  .. other stuff ...
} 
```

**Comment by seanparsons** [comment]
Isn't that going to break because the encode field isn't serializable?

**Comment by refried** [comment]
I recently saw some slides about a custom (proprietary?) Haskell compiler that could serialize lambdas, and it gave me hope.  But I don't think we'll be seeing this in Scala very soon.

**Comment by seanparsons** [comment]
@refried Well it's more of an issue with Java serialisation being a total face pain, it's annoying that Spark uses it to be honest.

**Comment by lvicentesanchez** [comment]
Spark uses java serialisation to serialise lambdas so that should work. Java serialisation sucks but as in scalding, I think they use it as a last resort to ensure that your program will work.

**Comment by tonymorris** [comment]
I should imagine it would be better to create an entirely new module, dependent on `argonaut`, that implements all these apologies and hacks, so that your program "works."

**Comment by seanparsons** [comment]
I think we can close this because it's not really something for Argonaut to do.
