### ISSUE TITLE
Auto encode/decode without defined implicit conversions

### ISSUE THREAD

**Issue by btbvoy** [argonaut-io/argonaut#166]
Are there some plans to introduce auto ("on the fly") encode/decode possibility. For instance so one can call .asJson and get object encoded to json without any implicit/explicit definition of how to encode/decode. For decoding operations desired Scala type should be provided for sure.

Please let me know, is it going to be added and in this case: when? :-) If it's already possible, please point me to how to do it :-)

Thank you in advance.

**Comment by seanparsons** [comment]
There aren't currently, mostly because it seems like it's fraught with shenanigans, auto codec derivation is in 6.1-M5 however: https://github.com/argonaut-io/argonaut/blob/master/src/main/scala/argonaut/CodecJson.scala#L31

**Comment by btbvoy** [comment]
There is a possibility to do it in jackson. But argonaut looks more elegant to me :-) So, I want to go with it. 

Thank you for pointing me to the existing implementation. Will check it out later today. 

*Just for my curiosity*: Is some help required for implementing such behaviour or it's mostly like feature for external plugin and not for core piece of library?

**Comment by seanparsons** [comment]
Well I don't see it being part of Argonaut currently because it's somewhat of a terrible idea because it would allocate the whole CodecJson instance each time you used the method.
