### ISSUE TITLE
upgrade monocle version to 1.1.0

### ISSUE THREAD

**Issue by julien-truffaut** [argonaut-io/argonaut#170]

**Comment by seanparsons** [comment]
I did start doing an upgrade to 1.something a couple of weeks ago, I should really revisit that.

**Comment by julien-truffaut** [comment]
I upgraded to 1.0.1 a few month back but I don't think it was released

**Comment by seanparsons** [comment]
@julien-truffaut Hmmm, maybe I'm thinking of 1.1.0, I'll double check when I get home.

**Comment by seanparsons** [comment]
Done.
