### ISSUE TITLE
Parse.parseOptional is not a valid optic

### ISSUE THREAD

**Issue by julien-truffaut** [argonaut-io/argonaut#171]
a `String` <-> `Json` is an unlawful `Prism` or `Optional`, example:

```scala
val json = jSingleObject("a"), jNumber(2))
parseOptional.getOption(" { a      :      2} ") == Some(json)
parseOptional.getOption(" { a      :      2} ").map(parseOptional.set(json)) == Some("{a:2}")
``` 
in other word formatting is not preserved by the optic. I noticed this issue on `Prism` that's why I made `parseOptional` an `Optional` (i.e. weaker `Prism`) but somehow I missed that the same issue is applicable to `Optional` :/

As far as I can tell, there is no lawful optic applicable here. Basically, I see 2 options:
* we remove `parseOptional` as it is broken
* we consider this optic useful so we add some doc to say that is unlawful (similar to `jDoublePrism`), if we go for this option, we could also make it a `Prism`: broken for broken, better get something more useful.

what are you thoughts?

**Comment by seanparsons** [comment]
If it's broken or unlawful it should go in my opinion, I didn't know about jDoublePrism...

**Comment by julien-truffaut** [comment]
It is fine with me to remove any unlawful optics

**Comment by seanparsons** [comment]
Looks to be gone to me.
