### ISSUE TITLE
Interactive chat for argonaut

### ISSUE THREAD

**Issue by btbvoy** [argonaut-io/argonaut#177]
Hi authors / contributors / maintainers of argonaut,

I found myself few times stuck with some questions regarding argonaut usage. Especially why something isn't working as expected (The one which is very popular isn't ? :-D). I didn't manage to find any specific interactive place like chat related to argonaut where I could ask some question.

**Question:** Could you create a room for instance in http://gitter.im or at any other public service like gitter and put a link to that chat into README.md so everyone who wants will join. It'll give ability to people who are using argonaut to group together and share knowledge & examples.

Thanks for very cool library and please give tools to community to grow by experience exchange.

Br,
Pavel

**Comment by seanparsons** [comment]
We have #argonaut on Freenode IRC network, which is where a few of us are about at various times, I'll put something on the readme about that.

**Comment by btbvoy** [comment]
Btw, that gitter.im service also supports IRC and it has some integrations with git repo. Might be someone of you will don't mind to create a room there as well. AFAIK it's free for open communities and repos. For those who used to use IRC - they provides a bridge to IRC clients via IRC protocol. 

Anyway thanks for info regarding IRC channel and if someone of you will decide to open the room in gitter please update me via comment in this topic :-)

**Comment by seanparsons** [comment]
If gitter can integrate with the IRC channel, that would be great. I'm dubious of there being more than one place for this.
