### ISSUE TITLE
Are nested classes supported?

### ISSUE THREAD

**Issue by Nutomic** [argonaut-io/argonaut#178]
(I couldn't find a support forum, so I'm asking here)

Can argonaut work well with JSON in the following format?

```
{
    "type": "ClassName",
    "data": {
        "var1": 1
        "var2": 2
    }
}
```

Where the fields in `data` differ between all classes.

I need this to parse the data [here](https://github.com/syncthing/syncthing/wiki/Event-Interface).

**Comment by seanparsons** [comment]
You'll be wanting the Getting Help section on this page: http://argonaut.io/

I'm not sure what you mean by nested classes, but it would be possible to make the field for data just Map[String, Json] or just make something with a whole load of fields that are Option[X].

**Comment by Nutomic** [comment]
That's what I expected. I'll see if it works in another library then.
