### ISSUE TITLE
Double behavior question

### ISSUE THREAD

**Issue by joshcough** [argonaut-io/argonaut#179]
I'm not sure if this is an error or not, but I'm getting strange behavior parsing a Double with quotes around it. Similar code works for Int, as shown below. So maybe this is a bug, or maybe I've missed a bit of documentation? If it isn't a bug, can someone point me in the right direction?

```scala
import scalaz._, Scalaz._
import argonaut._, Argonaut._

/**
 * Main prints:
 *   -\/(Double: [--\(d)])
 *   \/-(Dubble(56.45))
 *   \/-(Pint(56))
 *   \/-(Pint(56))
 */
object ArgonautDoubleWeirdness {

   case class Pint(i: Int)
   implicit def PintCodecJson: CodecJson[Pint] = casecodec1(Pint.apply, Pint.unapply)("i")

   case class Dubble(d: Double)
   implicit def DubbleCodecJson: CodecJson[Dubble] = casecodec1(Dubble.apply, Dubble.unapply)("d")

   def main (args: Array[String]) {
     println(Parse.decodeEither[Dubble]("""{"d":"56.45"}"""))
     println(Parse.decodeEither[Dubble]("""{"d":56.45}"""))
     println(Parse.decodeEither[Pint]("""{"i":"56"}"""))
     println(Parse.decodeEither[Pint]("""{"i":56}"""))
   }
 }
```

**Comment by joshcough** [comment]
Oh, I'm using sbt 0.13.8, scala 2.11.6, and "io.argonaut" %% "argonaut" % "6.1-M4" changing().

**Comment by markhibberd** [comment]
It is coded that way, but I don't think it has been thought about -
https://github.com/argonaut-io/argonaut/blob/master/src/main/scala/argonaut/DecodeJson.scala#L198-L200 vs https://github.com/argonaut-io/argonaut/blob/master/src/main/scala/argonaut/DecodeJson.scala#L206-L210

Basically, the Int codec explicitly checks for the String case, IIRC somewhere in the deep dark past this was added for compatibility with something (aeson perhaps) - I would suggest that double may have just been missed/overlooked. 

Having said that it is a pretty bizarre behaviour. Either int or double codec should probably change.

**Comment by markhibberd** [comment]
(if you want to work around it you would have to not use the convenience mechanism for the Dubble decoder, and basically implement the codec manually using the same technique as int does with the fallback to trying to decode a string).

**Comment by joshcough** [comment]
Thanks Mark. Would you be able to suggest a workaround for the Double issue for now? Or maybe the correct way to do Int and Double when they are quoted?

**Comment by joshcough** [comment]
Having Double behave like Int in this case seems to make sense to me. It just adds a little bit more flexibility, and I don't really see much of a downside. I'm not super familiar with the API yet though.

**Comment by joshcough** [comment]
I forked and implemented the fix as you described. I haven't added any tests though, but all the current tests do pass. I could send a pull request anyway, if you'd like.

**Comment by seanparsons** [comment]
If you could pull request those changes that would be grand.

**Comment by seanparsons** [comment]
The Double bit I've done coincidentally and I've added the Boolean thing as well.
