### ISSUE TITLE
Illegal field name using DecodeJson.derive (Argonaut 6.1)

### ISSUE THREAD

**Issue by ethul** [argonaut-io/argonaut#181]
The example below illustrates the issue. It seems that when a field name has a character that requires its declaration to be enclosed in backticks, the `DecodeJson.derive` macro generates an invalid class definition.

Please let me know if any other information would be helpful.

```scala
Welcome to Scala version 2.11.6 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_31).
Type in expressions to have them evaluated.
Type :help for more information.

scala> :paste
// Entering paste mode (ctrl-D to finish)

import argonaut._, Argonaut._

final case class Test(`a.b.c`: String)

object Test {
  implicit val decodeJson: DecodeJson[Test] =
    DecodeJson.derive[Test]
}

Parse.decodeEither[Test]("""{"a.b.c": "test"}""")

// Exiting paste mode, now interpreting.

java.lang.ClassFormatError: Illegal field name "a.b.c" in class Test$$anonfun$1
  at java.lang.ClassLoader.defineClass1(Native Method)
  at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
  at scala.reflect.internal.util.AbstractFileClassLoader.findClass(AbstractFileClassLoader.scala:64)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  ... 49 elided

scala>
```

**Comment by seanparsons** [comment]
That's...disappointing, thanks for the repro case though. Seems odd that this doesn't work though as I ponder it, makes me think that backtick handling happens at some weird step in the compiler chain.

**Comment by ethul** [comment]
Thanks for taking a look.

If it's of use, Play's [Json.reads](https://github.com/playframework/playframework/blob/a3741dc98700cb1bbedf0c9dc0cca35bf44ee129/framework/src/play-json/src/main/scala/play/api/libs/json/Json.scala#L194) ([macro implementation](https://github.com/playframework/playframework/blob/a3741dc98700cb1bbedf0c9dc0cca35bf44ee129/framework/src/play-json/src/main/scala/play/api/libs/json/JsMacroImpl.scala#L11-293)) does support this case.

**Comment by seanparsons** [comment]
It's also 10x the size of our implementation, this feels like it's going to be a pain to figure out.

**Comment by seanparsons** [comment]
@ethul Was actually an easy fix, if you need it ASAP it would be easy to snip the appropriate code as it's two small files, which can be merged together (they're done like that because of the way the macro API has changed).

**Comment by ethul** [comment]
Great! Thank you for the fix. I don't need it right away. I can wait for it in the next release.
