### ISSUE TITLE
Access and modify part of an arbitrary Json object

### ISSUE THREAD

**Issue by tsfto** [argonaut-io/argonaut#192]
Given this Json: 

    { "name" : "joe", "age": 21, "arbitraryJson": { "field1": "value1", "field2":"value2"} }

where the content of "arbitraryJson" can be any valid Json (i.e., this part of the schema is unknown),  I'd like to encode and decode it into class like this:

case class Person (name: String, age: Int, arbitraryJson: String )

with the arbitraryJson Base64-encoded/decoded. 

Is this possible with Argonaut? I've played around with various decoding and parsing tests, lenses and examples, but couldn't find anything that seemed to do something similar. I need to treat the entire Json tree below arbitrary Json as just a string, but it's not obvious how to do this.

Anyone have any examples of such a thing?

Thanks

**Comment by seanparsons** [comment]
Github issues aren't really the place for asking questions.

That said it would be possible to create EncodeJson and DecodeJson instances that translate to (String, Int, Json), probably by just using `implicitly[EncodeJson[(String, Int, Json)]]` for example and then mapping/contramapping what you get back to turn it into your desired type.
