### ISSUE TITLE
JsonNumber.toLong issue

### ISSUE THREAD

**Issue by julien-truffaut** [argonaut-io/argonaut#196]
```scala
JsonBigDecimal(BigDecimal(-1.92502709527405133E18)).toLong == Some(-1925027095274051330)
```

**Comment by julien-truffaut** [comment]
problem comes from `BigDecimal`:

```scala
BigDecimal(-1.92502709527405133E18).toLong
```

**Comment by seanparsons** [comment]
Is this dependent on the Monocle issue? As in is there anything to actually change in Argonaut to make this correct?

**Comment by seanparsons** [comment]
I'm guessing yes because of this:
```
scala> JsonNumber.fromString("-1.92502709527405133E18").get.toLong
res7: Option[Long] = Some(-1925027095274051330)
```

**Comment by julien-truffaut** [comment]
no it is related to `BigDecimal`

**Comment by seanparsons** [comment]
Ah, because the Prism is directly instantiating the JsonBigDecimal implementation?

**Comment by julien-truffaut** [comment]
the `Prism` call `JsonNumber.toLong` and it expects that if you get `Some(l)` then you can come back to the original `Json` using `jNumber`.

The problem is that `JsonNumber.toLong` succeeds even though the `JsonNumber` is not a `Long`.

**Comment by seanparsons** [comment]
Appears it's table flips all round then. :/

**Comment by seanparsons** [comment]
@julien-truffaut Right, now after spending a bit of time looking at this it appears the issue is actually with Doubles, I can reproduce it by creating a JsonDouble and then calling .toLong on that.

**Comment by seanparsons** [comment]
This little experiment appears to demonstrate the issue (`JsonDouble` checks the result of turning the Long back into a Double to see if it returns the same value):

```
scala> 3.1546052387411246E18
res5: Double = 3.1546052387411246E18

scala> 3.1546052387411246E18.toLong
res6: Long = 3154605238741124608

scala> 3.1546052387411246E18.toLong.toDouble
res7: Double = 3.1546052387411246E18
```

**Comment by seanparsons** [comment]
It's taken forever, but it would appear this is the root of all my problems:

```
scala> JsonDouble(3.1546052387411246E18).toBigDecimal == JsonBigDecimal(BigDecimal(3154605238741124608l)).toBigDecimal
res12: Boolean = false
```

That's what it appears is in turn causing the failure when it compares the numbers.

**Comment by seanparsons** [comment]
I've made a whole bunch of changes to master including retiring the JsonDouble representation of JsonNumber, which should make this all work. However in the process I've had to remove the Float and Double Prisms because they can cause bad times all around.
