### ISSUE TITLE
Found class scalaz.$bslash$div, but interface was expected

### ISSUE THREAD

**Issue by rimeh** [argonaut-io/argonaut#197]
I tested this example: 
  val requestJson =
    """
      |{
      |   "userid": "1"
      |}
      |""".stripMargin
  // parse the json and prepend a name field
  val updatedJson: Option[Json] = for {
    parsed <- requestJson.parseOption
  } yield ("name", jString("testuser")) ->: parsed
  // If there was a failure at any point, provide a default.
  val responseJson: Json = updatedJson.getOrElse{
    jSingleObject("error", jString("Something went wrong."))
  }
  println(responseJson.nospaces)

but I found as result:

java.lang.IncompatibleClassChangeError: Found class scalaz.$bslash$div, but interface was expected
	at argonaut.JsonParser$.expectObject(test.sc0.tmp:76)
	at argonaut.JsonParser$.argonaut$JsonParser$$expectValue(test.sc0.tmp:124)
	at argonaut.JsonParser$.parse(test.sc0.tmp:49)
	at argonaut.Parse$.parse(test.sc0.tmp:112)
	at argonaut.Parse$.parse(test.sc0.tmp:106)
	at argonaut.Parse$class.parseOption(test.sc0.tmp:36)
	at argonaut.Parse$.parseOption(test.sc0.tmp:106)
	at argonaut.ParseWrap.parseOption(test.sc0.tmp:39)
	at #worksheet#.updatedJson$lzycompute(test.sc0.tmp:12)
	at #worksheet#.updatedJson(test.sc0.tmp:11)
	at #worksheet#.#worksheet#(test.sc0.tmp:10)

I wrote in build.sbt:
name := "argonaut"
version := "1.0"
scalaVersion := "2.11.7"
libraryDependencies ++= {
  val akkaV = "2.3.6"
  val sprayV = "1.3.2"
  Seq(
    "io.spray"            %%  "spray-can"     % sprayV withSources() withJavadoc(),
    "io.spray"            %%  "spray-routing" % sprayV withSources() withJavadoc(),
    "io.spray"            %%  "spray-json"    % "1.3.1",
    "io.spray"            %%  "spray-testkit" % sprayV  % "test",
    "com.typesafe.akka"   %%  "akka-actor"    % akkaV,
    "com.typesafe.akka"   %%  "akka-testkit"  % akkaV   % "test",
    "org.specs2"          %%  "specs2-core"   % "2.3.11" % "test",
    "org.scalaz"          %%  "scalaz-core"   % "7.1.0",
    "io.spray"            % "spray-client_2.11" % "1.3.3",
    "io.argonaut"         %% "argonaut"       % "6.0.4"
  )
}

**Comment by seanparsons** [comment]
Argonaut 6.0 is incompatible with Scalaz 7.1, as it was built with Scalaz 7.0.

**Comment by rimeh** [comment]
I changed scalaz to 7.0 but I have : 
[error] (*:update) sbt.ResolveException: unresolved dependency: org.scalaz#scalaz-core_2.11;7.0: not found
[error] unresolved dependency: io.argonaut#argonaut_2.11;6.0: not found
[error] Total time: 3 s, completed Oct 22, 2015 2:51:27 PM

**Comment by seanparsons** [comment]
You need to specify specific versions of those, like Argonaut 6.0.4 rather than 6.0.
