### ISSUE TITLE
Error: could not find implicit value for evidence parameter of type spray.httpx.unmarshalling.FromResponseUnmarshaller     

### ISSUE THREAD

**Issue by rimeh** [argonaut-io/argonaut#198]
I have this two errors: 
could not find implicit value for evidence parameter of type 
Error:(40, 44) could not find implicit value for evidence parameter of type spray.httpx.unmarshalling.FromResponseUnmarshaller[test.GoogleApiResult]
    val pipeline = sendReceive ~> unmarshal[GoogleApiResult]
                                           ^
Error:(40, 44) not enough arguments for method unmarshal: (implicit evidence$1: spray.httpx.unmarshalling.FromResponseUnmarshaller[test.GoogleApiResult])spray.http.HttpResponse => test.GoogleApiResult.
Unspecified value parameter evidence$1.
    val pipeline = sendReceive ~> unmarshal[GoogleApiResult]
                                           ^
  
```scala
import scala.util.{Success, Failure}
import scala.concurrent.duration._
import akka.actor.ActorSystem
import akka.pattern.ask
import akka.event.Logging
import akka.io.IO
import spray.can.Http
import spray.client.pipelining._
import spray.util._
import argonaut._, Argonaut._

object test {

  case class Elevation(location: Location, elevation: Double)

  case class Location(lat: Double, lng: Double)

  case class GoogleApiResult(status: String, results: List[Elevation])

  implicit def locationFormat: CodecJson[Location] = casecodec2(Location.apply, Location.unapply)("lat", "lng")

  implicit def elevationFormat: CodecJson[Elevation] = casecodec2(Elevation.apply, Elevation.unapply)("location", "elevation")

  implicit def googleApiResultFormat: CodecJson[GoogleApiResult] = casecodec2(GoogleApiResult.apply, GoogleApiResult.unapply)("status", "results")


  object Main extends App {
    // we need an ActorSystem to host our application in
    implicit val system = ActorSystem("simple-spray-client")

    import system.dispatcher

    // execution context for futures below
    val log = Logging(system, getClass)

    log.info("Requesting the elevation of Mt. Everest from Googles Elevation API...")

    val pipeline = sendReceive ~> unmarshal[GoogleApiResult]

    val responseFuture = pipeline {
      Get("http://maps.googleapis.com/maps/api/elevation/json?locations=27.988056,86.925278&sensor=false")
    }
    responseFuture onComplete {
      case Success(GoogleApiResult(_, Elevation(_, elevation) :: _)) =>
        log.info("The elevation of Mt. Everest is: {} m", elevation)
        shutdown()

      case Success(somethingUnexpected) =>
        log.warning("The Google API call was successful but returned something unexpected: '{}'.", somethingUnexpected)
        shutdown()

      case Failure(error) =>
        log.error(error, "Couldn't get elevation")
        shutdown()
    }
    def shutdown(): Unit = {
      IO(Http).ask(Http.CloseAll)(1.second).await
      system.shutdown()
    }
  }

}
```
I need help thanks.

**Comment by julien-truffaut** [comment]
I am not familiar with spray but it seems that you need an instance of `FromResponseUnmarshaller[GoogleApiResult]`. I suppose you need to figure out how to hook an argonaut codec with a spray unmarshaller.

**Comment by rimeh** [comment]
If you know of links that can help me to understand  how to hook an argonaut codec with a spray unmarshaller, you can give me because I have searched but I can not find a solution.

thanks.

**Comment by seanparsons** [comment]
@rimeh Could you possibly take questions to the mailing list here please: https://groups.google.com/forum/?fromgroups#!forum/argonaut-json or the #argonaut IRC channel on Freenode, as Github issues aren't really the best place for said questions.
