### ISSUE TITLE
scalaz 7.2.0 support

### ISSUE THREAD

**Issue by jedws** [argonaut-io/argonaut#203]
Need to have a scalaz 7.2.0 supporting version. Not sure if this should be 6.2.x series or whether there should be cross-compilation, investigating.

**Comment by seanparsons** [comment]
This is done right @jedws? You posted the PR after all. :)

**Comment by jedws** [comment]
@seanparsons I think we only need to update the README such that argonaut 6.2 targets scalaz 7.2

**Comment by seanparsons** [comment]
Done.
