### ISSUE TITLE
After upgrade to 6.1 could not find implicit value for parameter e for case objects

### ISSUE THREAD

**Issue by jan0sch** [argonaut-io/argonaut#206]
Hi,

I just tried to update a project to argonaut 6.1 from 6.0.4 and I get several compile errors which seems to be related to `sealed trait` and `case object`.

For example code like this works fine with 6.0.4:

```scala
import argonaut._, Argonaut._

sealed trait StatusType {
  override def toString: String = this match {
    case StatusType.MinorError       ⇒ "MinorError"
    case StatusType.MajorError       ⇒ "MajorError"
    case StatusType.FatalError       ⇒ "FatalError"
  }
}

object StatusType {
  implicit def StatusTypeCodecJson: CodecJson[StatusType] =
    CodecJson(
      (s: StatusType) ⇒ jString(s.toString),
      c ⇒ for {
        s ← c.as[String]
      } yield s match {
        case "MinorError"       ⇒ MinorError
        case "MajorError"       ⇒ MajorError
        case "FatalError"       ⇒ FatalError
        case e: String          ⇒ throw new IllegalArgumentException(s"Unknown StatusType: '$e'!")
      }
    )

  case object MinorError extends StatusType
  case object MajorError extends StatusType
  case object FatalError extends StatusType
}
```

The code above also compiles without errors using 6.1, but if I try to compile something like `StatusType.MajorError.asJson` with argonaut 6.1 then I get an error like this:

````
[error] could not find implicit value for parameter e: argonaut.EncodeJson[StatusType.MajorError.type]
[error]   StatusType.MajorError.asJson
[error]                         ^
````

Any ideas how to solve this?

**Comment by seanparsons** [comment]
This is an unfortunate side effect of the loss of variance in 6.1 (which is likely to not be a problem in 6.2).

Unfortunately the type of StatusType.MajorError is StatusType.MajorError.type which extends StatusType, which the compiler is validly complaining doesn't have an instance for it. Until 6.2 the only way to fix this is to cast the object to the super type.

**Comment by jan0sch** [comment]
Thanks for the answer.
