### ISSUE TITLE
question: New modules naming convention

### ISSUE THREAD

**Issue by lvicentesanchez** [argonaut-io/argonaut#208]
I was wondering if it wouldn't be better to change the name of the object used to import the functionality of the new modules, `ArgonautScalaz`, `ArgonautMonocle` and `ArgonautCats`, to `scalaz`, `monocle` and `cats`.

If you wanted to use `argonaut` with `scalaz` support you would have to do this:

```scala
import argonaut._, Argonaut._
import argonaut.scalaz._
```

I prefer that over this:

```scala
import argonaut._, Argonaut._, ArgonautScalaz._
```

**Comment by seanparsons** [comment]
I'm not a huge fan of package objects personally, means if you want to go from importing all the instances with a wildcard it changes from a package import to an object import.

**Comment by lvicentesanchez** [comment]
I wasn't thinking on a proper package object but just a lowercased object name... link in scalaz.

**Comment by shawjef3** [comment]
I also prefer that over the current 6.2 way.

Another option is to just not use the package suffixes, which would be fine as long as people don't mind having to choose between scalaz, cats, or other implementations. That way argonaut-scalaz could be more of a drop-in replacement for Argonaut 6.1. Maybe even binary compatible.

**Comment by seanparsons** [comment]
For it's consistency with Scalaz at least (and the lack of a lot of people asking for this) I think it'll stay the way it is.
