### ISSUE TITLE
BigInt decoder may consume a lot of resources

### ISSUE THREAD

**Issue by travisbrown** [argonaut-io/argonaut#211]
The following hangs indefinitely, since the conversion from `BigDecimal("1e2147483647")` involves creating a `BigInt` with `Int.MaxValue` digits:

``` scala
argonaut.Parse.decode[BigInt]("1e2147483647")
```

I've got a fix coming for this in circe, but it's part of a much bigger `JsonNumber` overhaul, and you'll probably want to take a different approach here.

**Comment by lvicentesanchez** [comment]
@travisbrown could you point to the PR that fixes that in circe?

**Comment by seanparsons** [comment]
That's....upsetting.

**Comment by travisbrown** [comment]
@lvicentesanchez It's travisbrown/circe#189, but if you wanted to disentangle this fix you could just inspect the pieces of the underlying `java.math.BigDecimal` and fail the decoding instead of calling `toBigInteger` if the result will have more than some arbitrary (big) number of digits. I picked `2^18` digits, but that's just an offhand guess at a reasonable value.

**Comment by travisbrown** [comment]
@lvicentesanchez …it's worth noting that `2^18` is probably lower than it could reasonably be, but if someone wants to risk the performance cost they can always just `map` the `BigDecimal` decoder, so I think it makes sense to err on the small side.

**Comment by lvicentesanchez** [comment]
@travisbrown `2^18` seems a reasonable value, I will give it a thought over the weekend.
