### ISSUE TITLE
Unable to decode Byte with DecodeJson in argonaut 6.0.4

### ISSUE THREAD

**Issue by YuvalItzchakov** [argonaut-io/argonaut#214]
Running argonaut 6.1/6.0.4, I have the following LOC:
```
import argonaut.{DecodeJson, EncodeJson}

messageType <- (cursor --\ "messageType").as[Byte]
```
When attempting to compile, I receive the following error:

```
could not find implicit value for parameter e: argonaut.DecodeJson[Byte]
[error]  messageType <- (cursor --\ "messageType").as[Byte]
```

I can see that in the master branch, there's this method in "src/main/scala/argonaut/DecodeJson.scala":

```
implicit def ByteDecodeJson: DecodeJson[Byte] = {
    optionDecoder(x =>
      (x.number map (_.truncateToByte)).orElse(
      (x.string flatMap (s => tryTo(s.toByte)))), "Byte")
}
```
Yet it is absent in the 6.1 branch. Am I missing something?

**Comment by seanparsons** [comment]
Given when that was contributed (middle-ish last year) I would surmise that it was never pushed into the 6.1 series branch, it certainly wasn't in 6.0 at all.

I'll close this as it's going to be part of 6.2 and either the instances can be lifted from the code or the JSON number support can be leveraged to get a Byte.

**Comment by YuvalItzchakov** [comment]
I'm not sure I understand what "either the instances can be lifted from the code or the JSON number support can be leveraged to get a Byte." means, could you elaborate? Does this effectively mean that you can't parse out a Byte until 6.2?

**Comment by seanparsons** [comment]
They're just implicits you could include in your own code. Or you can decode it to the Json type and use the methods that optionally retrieve a JsonNumber and in turn a Byte from that.
