### ISSUE TITLE
Request for a milestone release depending on Scalaz 7.2

### ISSUE THREAD

**Issue by guersam** [argonaut-io/argonaut#215]
I'm trying to [update doobie](https://github.com/tpolecat/doobie/pull/254) to scalaz 7.2 and scalaz-stream 0.8a, but it fails to compile [tut](https://github.com/tpolecat/tut) documentation which depends on argonaut 6.1.

Would you consider cutting a milestone release?

**Comment by seanparsons** [comment]
6.2-M1 has been pushed to Maven central.

**Comment by guersam** [comment]
Thanks!
