### ISSUE TITLE
Create Gitter Space

### ISSUE THREAD

**Issue by briantopping** [argonaut-io/argonaut#216]
Could we get a Gitter space for users to help each other out? I think it's an easy first step to understanding common use cases such that the documentation in #89 could evolve.

**Comment by briantopping** [comment]
I created https://gitter.im/briantopping/argonaut in case anyone is interested in this. We can all move to the root Argonaut gitter when it gets created.

**Comment by seanparsons** [comment]
There is an IRC channel where a bunch of us tend to be, I'm amenable to creating a Gitter space, just dubious of there being a bunch of places to talk about Argonaut. Splitting down attention and numbers even further.

**Comment by briantopping** [comment]
Yah good point. I forgot about the IRC, the last time I tried it, the response to my question was lost because it came after I logged off.

**Comment by tylerjharden** [comment]
I say in favor of evolution you guys should honestly consider moving towards something like Gitter versus IRC, or setup some syndication between the two services. Every single Scala top-level project worth its salt is on Gitter, and I find it hugely beneficial to pop in and out of those channels to talk with the core devs and contributors.

**Comment by seanparsons** [comment]
@tylerjharden That somewhat assumes Gitter is better to be fair! :)

I don't think we'll move away from IRC, but as the core maintainer it means it's another thing vying for my attention!

**Comment by tylerjharden** [comment]
I do see your point there and I was rather shortsighted as I made that comment. Probably best to stick with whatever is most productive for you as core, and anyone from outside the core would rightfully adapt to said workflow if they wanted to involve themselves. 
Makes sense honestly. :)

Sent from Outlook on iOS




On Fri, Mar 18, 2016 at 2:26 PM -0700, "Sean Parsons" <notifications@github.com> wrote:












@tylerjharden That somewhat assumes Gitter is better to be fair! :)



I don't think we'll move away from IRC, but as the core maintainer it means it's another thing vying for my attention!

**Comment by seanparsons** [comment]
I've created the Gitter room.

**Comment by tonymorris** [comment]
To achieve what practical benefit?

**Comment by seanparsons** [comment]
@tonymorris Easier for those who don't use IRC to ask questions, I'm personally using the Gitter IRC bridge however.

**Comment by briantopping** [comment]
https://github.com/finnp/gitter-irc-bot
