### ISSUE TITLE
Json DSL for Monocle

### ISSUE THREAD

**Issue by hvesalai** [argonaut-io/argonaut#217]
Hi,

The basic monocle API is quite verbose and the monocle DSL is hidious. So I wrote my own DSL, that looks basically like this: `val p = jObjectPrism \ "foo" \ "zot" \ each \ "bar" \ jStringPrism`, which I'd say is very readable.

If anybody is interested, I can make a pull request, but if this looks like something you don't like, then I won't mind you just closing the issue.

Heikki

```scala
object MyMonocleDSL {
    import argonaut._, Argonaut._
    import monocle.function.index
    import monocle.std.list._
    import monocle.{Prism, Optional, Traversal}

    // export each so that the consumer doesn't need to import it separately
    val each = monocle.function.each[JsonArray, Json]

    implicit class PrismImplicits(p: Prism[Json, JsonObject]) {
      def \(field: String) = p.composeOptional(index(field))
    }

    implicit class OptionalImplicits(p: Optional[Json, Json]) {
      def \(field: String) = p.composePrism(jObjectPrism).composeOptional(index(field))
      def \(f: Traversal[JsonArray, Json]) = p.composePrism(jArrayPrism).composeTraversal(f)
      def \[T](p2: Prism[Json, T]) = p.composePrism(p2)
    }

    implicit class JsonTraversalImplicits(p: Traversal[Json, Json]) {
      def \(field: String) = p.composePrism(jObjectPrism).composeOptional(index(field))
      def \(f: Traversal[JsonArray, Json]) = p.composePrism(jArrayPrism).composeTraversal(f)
      def \[T](p2: Prism[Json, T]) = p.composePrism(p2)
    }

    implicit class JsonObjectTraversalImplicits(p: Traversal[Json, JsonObject]) {
      def \(field: String) = p.composeOptional(index(field))
    }
  }
```

**Comment by seanparsons** [comment]
I wonder if this would make more sense in a generalised style for Monocle itself, what do you think @julien-truffaut?

**Comment by hvesalai** [comment]
I think this would not work as generic Monocle DSL since it is JSON specific, i.e. one DSL operation maps to several Monocle operations. For example `\ "foo"` implicitly knows that since we are accessing a field from Json, a jObjectPrism must be applied first.

**Comment by julien-truffaut** [comment]
There is definitely a benefit to create such a DSL. I know that travis started one in circe and stacy is planning one in pimpathon. Btw `each` can both be applied to Json array and object.

**Comment by hvesalai** [comment]
Traversing the fields would the be just: `jObjectPrism \ "foo" \ jObjectPrism \ each`

**Comment by julien-truffaut** [comment]
probably #236 covers it, what do you think @hvesalai

**Comment by seanparsons** [comment]
I'm invoking executive privileges on this one!
