### ISSUE TITLE
Move jawn module here?

### ISSUE THREAD

**Issue by rossabaker** [argonaut-io/argonaut#218]
jawn-argonaut is built against Argonaut 6.1, and is binary incompatible with argonaut-6.2-M1.  The Jawn facade API is stable, whereas Argonaut's core is still evolving.  It makes more sense to me for jawn+argonaut integration to live in Argonaut rather than Jawn, so there's always a compatible release for the faster moving library.  Would a PR for this be welcome?

non/jawn#49

**Comment by seanparsons** [comment]
A PR for that would definitely be welcome, it _seems_ like it would make sense to track it here.
