### ISSUE TITLE
Make JsonIdentity support encoders in parent companion objects

### ISSUE THREAD

**Issue by shawjef3** [argonaut-io/argonaut#228]
I expected the following to compile, but it doesn't. Maybe there's another pattern I'm supposed to use.

```scala
Singleton0.asJson

sealed trait Singleton

object Singleton {
  implicit val codec: CodecJson[Singleton] = ???
}

case object Singleton0 extends Singleton

case object Singleton1 extends Singleton
```

> Error:(46, 14) could not find implicit value for parameter e: argonaut.EncodeJson[com.rocketfuel.server.rfi.dataexchange.ubx.Singleton0.type]
  Singleton0.asJson
>              ^

**Comment by shawjef3** [comment]
For now I'm getting around this with

```scala
(Singleton0 : Singleton).asJson
```

**Comment by seanparsons** [comment]
If you're using 6.1 this is a variance issue which was introduced in that version and undone in 6.2.
