### ISSUE TITLE
No implicit encode/decode for Seq[T] in 6.2-M1

### ISSUE THREAD

**Issue by jvliwanag** [argonaut-io/argonaut#229]
There used to be implicit encoder/decoder for something `Seq[T]` in 6.1.x. However, this no longer works for 6.2-M1. `List[T]` and `Vector[T]` works fine though.

Looks like this was removed by 28953e2 since it depended on the old implicit `CanBuildFrom`. Is support for `Seq` really going away for 6.2?

**Comment by seanparsons** [comment]
Seq is the stuff of nightmares because of variance, it's effectively a case of pick one of a) variance for the typeclasses or b) variance for that type.
