### ISSUE TITLE
Publish 6.2-M2

### ISSUE THREAD

**Issue by jedesah** [argonaut-io/argonaut#235]
`monocle` just upgraded to `scalaz` `7.3.0-M3` [here](https://github.com/julien-truffaut/Monocle/commit/13093b1eef33df4fc0485e5bf4b320fe14a468fd) which is breaking builds for people using `argonaut` `6.2-M1`.

The dependency on a `monocle` `SNAPSHOT` has since been removed from `argonaut` on master so it seems to me that simply publishing a new milestone release would solve this problem for everyone depending on `6.2-M1`.

**Comment by seanparsons** [comment]
6.2-M2 has been pushed and I've confirmed that it's on Maven Central.
