### ISSUE TITLE
Support both scalaz 7.1 and 7.2 in argonaut-scalaz 6.2

### ISSUE THREAD

**Issue by gwils** [argonaut-io/argonaut#237]
I propose that argonaut-scalaz 6.2 come in two flavours: argonaut-scalaz 6.2, which uses scalaz 7.1, and argonaut-scalaz-6.2a, which uses scalaz 7.2

This is in line with the practice of projects like [http4s](https://github.com/http4s/http4s), and makes it easier for heavy scalaz users to migrate from argonaut 6.1 -> 6.2.

This is causing my team some pain right now. Please see my http4s issue [here](https://github.com/http4s/http4s/issues/640).

**Comment by reactormonk** [comment]
Possibly by porting over https://github.com/http4s/http4s/blob/master/project/Http4sBuild.scala

**Comment by seanparsons** [comment]
Hmmm, I'm tempted to go with a suffix on the version of scalaz. then we could have:

- 6.2
- 6.2-scalaz-7.1
- 6.2-scalaz-7.3

Just so as to make it a tiny bit more flexible and avoid any vagueness around say what 6.2a actually means.

**Comment by gwils** [comment]
That kind of suffixing looks good to me.

I personally don't need this anymore though, all I need is an argonaut 6.2 with scalaz 7.2, so that I can get that argonaut into http4s, and then update my stack to scalaz 7.2 everywhere :)
