### ISSUE TITLE
Cannot compile code from example

### ISSUE THREAD

**Issue by cokleisli** [argonaut-io/argonaut#242]
scala> import argonaut._
import argonaut._

scala> import Argonaut._
import Argonaut._

scala> import scalaz._
import scalaz._

scala> import Scalaz._
import Scalaz._

scala> val jsonString: Json = jString("JSON!")
java.lang.IncompatibleClassChangeError: Found class scalaz.Memo, but interface was expected
  at argonaut.PrettyParams.<init>(PrettyParams.scala:112)
  at argonaut.PrettyParamss$class.$init$(PrettyParams.scala:252)
  at argonaut.Argonaut$.<init>(Argonaut.scala:3)
  at argonaut.Argonaut$.<clinit>(Argonaut.scala)
  ... 43 elided

build.sbt
  "io.argonaut" %% "argonaut" % "6.1",
  "org.scalaz" %% "scalaz-core" % "7.2.4",

**Comment by cokleisli** [comment]
Works with scalaz 7.1.1.

**Comment by julien-truffaut** [comment]
I believe you need to use argonaut `6.1a` with scalaz `7.2.x`

**Comment by seanparsons** [comment]
Yup, Argonaut 6.1 is tied to Scalaz 7.1.
