### ISSUE TITLE
IndexOutOfBoundsException in vectorMemo

### ISSUE THREAD

**Issue by paulp** [argonaut-io/argonaut#243]
We see periodic test failures on travis (such as [this one](https://travis-ci.org/quasar-analytics/quasar/jobs/153079887)) with stack trace
```
[error]      java.lang.IndexOutOfBoundsException: 0 (PrettyParams.scala:97)
[error] argonaut.PrettyParams$$anonfun$vectorMemo$1.apply(PrettyParams.scala:97)
[error] argonaut.PrettyParams$$anonfun$vectorMemo$1.apply(PrettyParams.scala:92)
[error] argonaut.PrettyParams.argonaut$PrettyParams$$lbrace$1(PrettyParams.scala:147)
[error] argonaut.PrettyParams$$anonfun$argonaut$PrettyParams$$trav$1$6.apply(PrettyParams.scala:190)
[error] argonaut.PrettyParams$$anonfun$argonaut$PrettyParams$$trav$1$6.apply(PrettyParams.scala:189)
[error] argonaut.Json.fold(Json.scala:33)
[error] argonaut.PrettyParams.argonaut$PrettyParams$$trav$1(PrettyParams.scala:171)
[error] argonaut.PrettyParams.pretty(PrettyParams.scala:203)
[error] argonaut.Json.pretty(Json.scala:420)
```
The code in question is
```
    89	  private[this] def vectorMemo(f: Int => String): Int => String = {
    90	    var vector: Vector[String] = Vector.empty
    91
    92	    (i: Int) => {
    93	      if (i >= 0) {
    94	        if (vector.size <= i) {
    95	          vector = vector ++ Vector.tabulate(i + 1 - vector.size)(n => f(n + vector.size))
    96	        }
    97	        vector(i)
    98	      } else {
    99	        ""
   100	      }
   101	    }
   102	  }
```
I won't speculate on exactly how the IOOB comes to pass, but the evidence suggests that this could use some hardening before indexing into vector on line 97.

**Comment by seanparsons** [comment]
This has that whiff of race condition/memory coherence about it, which I'm surprised by looking at it.

**Comment by paulp** [comment]
Yeah, that was the speculation I held back. I will suppose the var has to be marked @volatile.

**Comment by paulp** [comment]
Doing so produces a whole different class for the Vector reference - VolatileObjectRef rather than ObjectRef.

**Comment by seanparsons** [comment]
Worst kind of thing to test as well.

I see a couple of solutions:

- Add @volatile, hope for the best.
- Bin it off completely and just deal with the performance hit, probably worth double checking how much effect this actually has.
- Pre-warm the vectors on construction of PrettyParams up to say like 5 as that might stave off 99.9% of these.

**Comment by paulp** [comment]
Either of the first two sounds pretty reasonable to me, not such a fan of the third.

**Comment by paulp** [comment]
This continues to be a regular occurrence. I noticed something today which I don't remember seeing before - a non-zero index. I don't know if that reveals anything interesting.
```
[error]      java.lang.IndexOutOfBoundsException: 2 (PrettyParams.scala:97)
[error] argonaut.PrettyParams$$anonfun$vectorMemo$1.apply(PrettyParams.scala:97)
[error] argonaut.PrettyParams$$anonfun$vectorMemo$1.apply(PrettyParams.scala:92)
[error] argonaut.PrettyParams.argonaut$PrettyParams$$rbrace$1(PrettyParams.scala:150)
...
```

**Comment by seanparsons** [comment]
@paulp Apologies, all the other things have kept me from sitting down and looking at this.

It looks to be confirming the earlier hypothesis that it's a race condition.

Glancing at the Quasar code it looks like it'll create PrettyParams instances quite a lot as they're attached to `JsonOps`. Moving those instances onto an object might drastically reduce the occurrence of this until the issue is fixed.

**Comment by seanparsons** [comment]
Fingers crossed the commit above should at least prevent this issue from recurring.
