### ISSUE TITLE
publish for Scala 2.12?

### ISSUE THREAD

**Issue by SethTisue** [argonaut-io/argonaut#246]
has any effort been made to publish artifacts for e.g. Scala 2.12.0-RC1?

(are any upstream dependencies missing? if so, let's contact their maintainers)

**Comment by julien-truffaut** [comment]
monocle is waiting on shapeless (see https://github.com/julien-truffaut/Monocle/pull/397). `core` module should be fine.

**Comment by seanparsons** [comment]
I might hold off a 6.2 release to get 2.12 support in there, even if only for an RC version just because that would work out quite nicely.

**Comment by xuwei-k** [comment]
https://github.com/argonaut-io/argonaut/pull/250

**Comment by hamnis** [comment]
2.12.0 is out. http://www.scala-lang.org/news/2.12.0

**Comment by xuwei-k** [comment]
depends on https://github.com/typelevel/cats/pull/1450

**Comment by xuwei-k** [comment]
https://github.com/argonaut-io/argonaut/pull/251

**Comment by xuwei-k** [comment]
https://oss.sonatype.org/content/repositories/releases/io/argonaut/argonaut_2.12/6.2-RC1/
