### ISSUE TITLE
Does `spaces2` produce Unix style line endings by default

### ISSUE THREAD

**Issue by tobyweston** [argonaut-io/argonaut#268]
Quick question; does the `spaces2` method with the default prettifier (`spaces2.pretty`) produce unix style line endings (`LF`) by default? I'm seeing `LF`s in windows machines where i'd expect `CR+LF`.

I see a lot of `\n` characters in there but aren't sure if that's the intention. Should they be replaced with 

   sys.props("line.separator")

or is there a way to configure it?

**Comment by seanparsons** [comment]
@tobyweston There is a way to configure it using PrettyParams: https://github.com/argonaut-io/argonaut/blob/master/argonaut/shared/src/main/scala/argonaut/PrettyParams.scala#L275

You just need to create an instance that works to your particular requirements and invoke the `pretty` function on that.

Unless there's a strong reason for using platform line separators, I don't think the defaults should change because thar be dragons.

**Comment by tobyweston** [comment]
Thanks,

I went for this:

```
  val eol = sys.props("line.separator")
  val x: PrettyParams = PrettyParams(
    indent = "  "
    , lbraceLeft = ""
    , lbraceRight = eol
    , rbraceLeft = eol
    , rbraceRight = ""
    , lbracketLeft = ""
    , lbracketRight = eol
    , rbracketLeft = eol
    , rbracketRight = ""
    , lrbracketsEmpty = ""
    , arrayCommaLeft = ""
    , arrayCommaRight = eol
    , objectCommaLeft = ""
    , objectCommaRight = eol
    , colonLeft = " "
    , colonRight = " "
    , preserveOrder = false
    , dropNullKeys = false
  )

...

  x.pretty(json)))

```

Curious though what kind of issues you're thinking of ('thar be dragons')? 

I'm interested because when we develop our app on different platforms (it's open source), the tests will fail on Windows (doing string comparisons of JSON). 

I can use the above to fix this but having seconds thoughts, should I be wary? The deployment server is unix but clients (consuming the JSON) will be multi-platform using arbitrary JSON decoding libraries and include browsers, Browsers won't be weird with line endings surely?!

**Comment by seanparsons** [comment]
Doing string comparisons on JSON is pretty dangerous given that there's no guaranteed ordering of the key value pairs inside objects as well as the line ending issue. So even if it was purely a *nix environment you'd likely have issues with that anyway.
