### ISSUE TITLE
Expose `decodeAll` Function to Handle All Decoding Failures?

### ISSUE THREAD

**Issue by kevinmeredith** [argonaut-io/argonaut#275]
Recently, at work, I had a need to decode an `A`, listing all decoding errors.

I didn't find any existing function, so I wrote a `DecodeJson[A]` using `scalaz.ValidationNel`. So, the out of the box `DecodeJson`, which had fit my needs in the past, didn't cut it in this specific case.

Looking at the existing `jdecode2L`:

```scala
case class Foo(x: Int, y: String)

scala> val fooDecode: DecodeJson[Foo] = jdecode2L(Foo.apply)("x", "y")
decode: argonaut.DecodeJson[Foo] = argonaut.DecodeJson$$anon$1@75540185
```

Then, attempting to decode `Json` having invalid `x` and `y` JSON keys' values, the decoder fails fast on `x`:

```scala
scala> fooDecode.decode("""{"x" : false, "y" : true}""".parse.toEither.right.get.hcursor)
res11: argonaut.DecodeResult[Foo] = DecodeResult(-\/((Int,CursorHistory([--\(x)]))))
```

If it doesn't already exist, would it be worthwhile to provide such a function?

```scala
import scalaz._, Scalaz._
import argonaut._

// warning - c.history in the `Failure` case seems wrong to me
def decodeAll[A](f: HCursor => ValidationNel[String, A]): DecodeJson[A] = 
  new DecodeJson[A] {
     def decode(c: HCursor): DecodeResult[A] = f(c) match {
          case Success(a)   => DecodeResult.ok(a)
          case Failure(err) => DecodeResult.fail(err.show.toString, c.history) 
     }
  }
```

Related - https://stackoverflow.com/questions/44853197/decodejson-with-all-failed-decoding-attempts

**Comment by seanparsons** [comment]
@kevinmeredith Please feel free to create a PR for it (ideally with some tests :)), that sounds like a useful addition to me.
