### ISSUE TITLE
jObjectPL not found in 6.2

### ISSUE THREAD

**Issue by thunderkid** [argonaut-io/argonaut#283]
I've just switched from 6.1 to 6.2 and suddenly my lenses don't work since `jObjectPL` is no longer defined. But the docs for lenses still reference it. Am I missing something trivial?

**Comment by julien-truffaut** [comment]
@thunderkid I believe optics have been moved to either scalaz (`argonaut-scalaz`) or monocle (`argonaut-monocle`) module of argonaut

**Comment by seanparsons** [comment]
@thunderkid @julien-truffaut Yup: https://github.com/argonaut-io/argonaut/blob/114f1e1eb2ea25fef17b175c1c6c14a6f1dbc0fd/argonaut-scalaz/shared/src/main/scala/argonaut/JsonScalaz.scala

**Comment by sworisbreathing** [comment]
Not to beat a dead horse here, but can someone please update the docs to make this a bit more clear? http://argonaut.io/doc/zipper/#lenses doesn't mention that we need to add another module dependency.
