### ISSUE TITLE
Examples missing from the docs and README

### ISSUE THREAD

**Issue by elsehow** [argonaut-io/argonaut#284]
[Link to examples from README](https://github.com/argonaut-io/argonaut/tree/master/argonaut/jvm/src/test/scala/argonaut/example) is broken, and [docs won't load on argonaut.io](http://argonaut.io/doc/parsing/)

**Comment by seanparsons** [comment]
Wow, I updated everything to 6.2 last night, so that was a quick catch.

**Comment by seanparsons** [comment]
All fixed!
