### ISSUE TITLE
Parsing a list of heterogeneous types sharing a common ancestor class

### ISSUE THREAD

**Issue by elsehow** [argonaut-io/argonaut#285]
(I asked this on the Gitter channel, which appears to be quiet - apologies if this is the wrong place to post this request).

I have JSON that looks like this:

```json
{
   "events":[
      {
         "type":"trade",
         "tid":1111597035,
         "price":"2559.98",
         "amount":"0.07365713",
         "makerSide":"ask"
      },
      {
         "type":"change",
         "side":"ask",
         "price":"2559.98",
         "remaining":"20.98651537",
         "delta":"-0.07365713",
         "reason":"trade"
      }
   ]
}
```

Say that I model both of the objects in this `events` list as subclasses of an abstract class `MarketEvent`.

Is  there an idiomatic way to parse this list `.as[List[MarketEvent]]`?

Thanks for any help. I suspect this sort of situation is common enough, so perhaps it could make a nice addition to the docs.

**Comment by seanparsons** [comment]
@elsehow If you have a `DecodeJson`/`CodecJson` for `X`, then with the stock imports you get that for `List[X]` as well:

```
"[1,2,3]".decodeEither[List[Int]]
```

**Comment by elsehow** [comment]
@seanparsons I understand that this would work if I had a codec for `MarketEvent`. My question is how to get such a codec, when the actual return type is unclear.

For example, a Codec for `MarketEvent` would never actually return a `MarketEvent`, but rather a subclass (`TradeEvent` or `ChangeEvent` in this example).

**Comment by seanparsons** [comment]
@elsehow Right I understand the issue now.

The reason why we don't particularly have documentation for this kind of thing is that there's a few ways that it can be tackled and it depends on the data itself. One way is to write `DecodeJson` instances for each subclass, use `widen` to make pull those up to the superclass type and then compose them with the `|||` operator. Alternatively some people use `DecodeJson.apply` and write the appropriate code to flip between different decoders based on values within the JSON (like your `type` field above).

**Comment by elsehow** [comment]
@seanparsons That makes sense! Perhaps a couple "recipes" would be nice, with some trivial example. I spent a lot of time searching around for answers to this, and it's common enough in the JSON world that others might be interested as well.

Thank you for the help!

**Comment by seanparsons** [comment]
Please feel free to PR something for the docs, if it's written by someone that is wrestling with it then it'll probably be clearer than anything written by a person that has been using the library for 5 years!

**Comment by elsehow** [comment]
Sounds good. I'll do a PR if I solve my issue!
