### ISSUE TITLE
6.2 support for cats needs to move to 1.0.0-RC1

### ISSUE THREAD

**Issue by coltfred** [argonaut-io/argonaut#286]
Cats released 1.0.0-RC1 a couple days ago. We need to get a 6.2 version which is built on top of it. 

How would you like to handle the version number? The code changes should be very small.

**Comment by seanparsons** [comment]
I'm reopening this to track the need for a new release.

**Comment by rossabaker** [comment]
Is the plan to release on the heels of cats-1.0?  This is blocking me from upgrading some intermediate libraries.

Thanks!

**Comment by seanparsons** [comment]
@rossabaker I'm somewhat hesitant to push a special release if the final version is close.

**Comment by rossabaker** [comment]
Sorry, that's what I meant.  I was hoping another release could be done very quickly after cats-1.0, and then downstream projects would be able to release as well.  I can prepare downstream projects with a local build in the meantime.

**Comment by seanparsons** [comment]
@rossabaker Yeah, that's my plan. When the final release is cut I'll push another Argonaut release to match it.
