### ISSUE TITLE
jObjectPL and friends still broken on version 6.2

### ISSUE THREAD

**Issue by CathDalzell** [argonaut-io/argonaut#310]
As noted in a previous "issue", following the instructions in the documentation about lenses yields an error when calling jObjectPL -- it can't be found. I get that the lenses are defined in argonaut-scalaz, but the given sbt and import statements are not getting the job done.

I refer to 
`"io.argonaut" %% "argonaut" % "6.2"` in SBT

and` import argonaut._, Argonaut._, scalaz._, Scalaz._`

The documentation says something about using argonaut-monocle, but trying to import argonaut-monocle also produced an error.

**Comment by xuwei-k** [comment]
try `import argonaut.JsonScalaz._`

https://github.com/argonaut-io/argonaut/blob/v6.2.2/argonaut-scalaz/shared/src/main/scala/argonaut/JsonScalaz.scala#L40
