### ISSUE TITLE
Publish for 2.13.0-M5

### ISSUE THREAD

**Issue by alexarchambault** [argonaut-io/argonaut#319]
It seems `2.13.0-M5` is supported on master, but no version with it is published yet.

**Comment by alexarchambault** [comment]
Let me know if I can do anything to help. (I can help set up [sbt-ci-release](https://github.com/olafurpg/sbt-ci-release) to automate releases for example.)

**Comment by seanparsons** [comment]
@xuwei-k I should really sort you out with the ability to publish, I've got very limited time at the moment and don't want to be a bottleneck/blocker.

**Comment by xuwei-k** [comment]
https://issues.sonatype.org/browse/OSSRH-4952?focusedCommentId=642017

I have request permission for publish.

**Comment by xuwei-k** [comment]
6.2.3 released https://repo1.maven.org/maven2/io/argonaut/argonaut_2.13.0-M5/
