### ISSUE TITLE
re-enable travis-ci

### ISSUE THREAD

**Issue by xuwei-k** [argonaut-io/argonaut#322]
https://travis-ci.org/argonaut-io/argonaut 🤔 

![93A5FB5A-F105-4084-B886-9F9ADB9B0C00](https://user-images.githubusercontent.com/389787/54693546-32a80700-4b6a-11e9-965e-ebf54b601e48.jpeg)

**Comment by seanparsons** [comment]
Huh, oddly I can't sign into Travis, the sign in link just cycles some redirects and then I end up back in the same place still logged out.

**Comment by xuwei-k** [comment]
Hmm, Could you give me admin permissions on this repo?

**Comment by seanparsons** [comment]
@xuwei-k Done.

**Comment by xuwei-k** [comment]
Thanks!
