### ISSUE TITLE
publish for 2.13.0-RC1

### ISSUE THREAD

**Issue by Milyardo** [argonaut-io/argonaut#324]
would be great to get testing with that

**Comment by xuwei-k** [comment]
- https://repo1.maven.org/maven2/io/argonaut/argonaut_2.13.0-RC1/
- https://repo1.maven.org/maven2/io/argonaut/argonaut-scalaz_2.13.0-RC1/

**Comment by xuwei-k** [comment]
TODO
- [ ] argonaut-cats https://github.com/typelevel/cats/issues/2776
- [ ] argonaut-monocle https://github.com/julien-truffaut/Monocle/issues/654
- [ ] argonaut-jawn https://github.com/typelevel/jawn/issues/160
