### ISSUE TITLE
Stream-based reading and writing

### ISSUE THREAD

**Issue by nrinaudo** [argonaut-io/argonaut#52]
As far as I can tell (and I might very well be wrong), argonaut currently only knows how to read from / write to strings.

This seems like a suboptimal solution for cases where, for example, one wants to read a tiny JSON object from a file that happens to contains gigabytes of whitespace padding.

It seems that, at least for the input part, solving this could be as simple as having the `Parser` work with instances of `Iterator[Char]` or `Iterable[Char]`: both `String` and `Source` are collections of characters and can be transformed into an iterator on characters fairly easily.

Or is this possibly because having a string, and thus knowing the amount of data to parse, allows for drastic parsing optimisations?

**Comment by i-am-the-slime** [comment]
Is there any progress on this?

**Comment by seanparsons** [comment]
@i-am-the-slime Nope, I'm tempted to close this for now as otherwise it's just an issue hanging around forever. If anything I'd much rather there be separate projects for this because there's not one stream type to integrate with.

**Comment by briantopping** [comment]
@seanparsons Are there separate projects already or just opining that there should be separate projects if this issue were to be resolved?

**Comment by seanparsons** [comment]
Opining, as there would need to countless implementations.
