### ISSUE TITLE
Can we donate to argonaut.io domain

### ISSUE THREAD

**Issue by tapinambur0508** [argonaut-io/argonaut#560]
Hello! Can we help extend the argonaut.io domain for documentation? Without it, it is very difficult to use the library

**Comment by tapinambur0508** [comment]
Also a good offer, but we do not have them

**Comment by chace86** [comment]
I am trying to find examples of validation (max length of field or if one field exists, another must be present).

It is really hard to navigate this library without docs.

**Comment by mikecarr2** [comment]
There has been some [security research published](https://blog.oversecured.com/Introducing-MavenGate-a-supply-chain-attack-method-for-Java-and-Android-applications), dubbed MavenGate, that indicates that by not renewing the domain an attacker could embed malicious code within published versions of the library.

**Comment by michaelmior** [comment]
While it doesn't help with published version of the library, one solution could be to switch the group to `io.github.argonaut-io`.

**Comment by xuwei-k** [comment]
groupId changed and 6.3.11 released

- https://repo1.maven.org/maven2/io/github/argonaut-io/
- https://github.com/argonaut-io/argonaut/commit/a0a314e7fd4c38c207ceea2539aac973ac8d551f
- https://github.com/argonaut-io/argonaut/commit/af7407216bf75c5f773ba4bb181552802084e9c2
