### ISSUE TITLE
Investigate alternative codec implementations for Double and Option using type tags.

### ISSUE THREAD

**Issue by markhibberd** [argonaut-io/argonaut#66]

**Comment by refried** [comment]
+1

**Comment by refried** [comment]
I see PrettyParams.dropNullKeys was added in c8e526dbc9d6d15447b822735bcb0bc510cdbf00.  Works fine for me, thanks.

**Comment by etrain** [comment]
Just FYI - The `PrettyParams.dropNullKeys` thing is exactly what I was looking for but I had to dig up this thread to find it. Here's a simple example using `6.2-RC2` for future readers of this thread:

```
import argonaut._, Argonaut._
val customPrinter = nospace.copy(dropNullKeys = true)
obj.asJson.pretty(customPrinter)
```
