### ISSUE TITLE
Separate JArray and JObject commas in PrettyParams

### ISSUE THREAD

**Issue by seigert** [argonaut-io/argonaut#92]
With current comma formatting it seems impossible to me to pretty print one-line arrays and multi-line objects at same time:
```
{
  "array" : [ "a", "b", "c" ],
  "data" : "value",
  "another" : "value"
}
```

This issue could be resolved by separating `commaLeft` & `commaRight` attributes in `PrettyParams` into `arrayCommaLeft`, `arrayCommaRight`, `objectCommaLeft` & `objectCommaRight`.

**Comment by seanparsons** [comment]
I think these are pretty much done, I've made a slight tweak to the PrettyParams.pretty method which makes empty arrays a bit more flattened out.
